# **Project**

The aim of this project is to use a dataset of the Dow Jones Index to determine which quarters had what kind of growth during the timeframe of the dataset

![Project Description](project_desc.png)

Anyone can use this Notebook with ease. Nothing extra is required by the user since the raw (cleaned) data is included as a file in the same folder as this Notebook. Same goes for any images, since they also are in the same folder. Also if the user of the notebook wants to acces the data without having to do anything special, they can go to the un-ran cell where it says "RUN THIS TO GET THE RAW DATA"

In [1]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in c:\users\axel\anaconda3\lib\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in c:\users\axel\anaconda3\lib\site-packages (from ucimlrepo) (2.3.3)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\axel\anaconda3\lib\site-packages (from ucimlrepo) (2026.4.22)
Requirement already satisfied: numpy>=1.26.0 in c:\users\axel\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\axel\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\axel\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\axel\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\axel\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
dow_jones_index = fetch_ucirepo(id=312) 
  
# data (as pandas dataframes) 
X = dow_jones_index.data.features 
y = dow_jones_index.data.targets 

# variable information 
display(dow_jones_index.variables)

,name,role,type,demographic,description,units,missing_values
0,quarter,Feature,Integer,None,None,None,no
1,stock,Feature,Categorical,None,None,None,no
2,date,Feature,Date,None,None,None,no
3,open,Feature,Categorical,None,None,None,no
4,high,Feature,Categorical,None,None,None,no
5,low,Feature,Categorical,None,None,None,no
6,close,Feature,Categorical,None,None,None,no
7,volume,Feature,Integer,None,None,None,no
8,percent_change_price,Feature,Continuous,None,None,None,no
9,percent_change_volume_over_last_wk,Feature,Continuous,None,None,None,no
10,previous_weeks_volume,Feature,Integer,None,None,None,no
11,next_weeks_open,Feature,Categorical,None,None,None,no
12,next_weeks_close,Feature,Categorical,None,None,None,no
13,percent_change_next_weeks_price,Target,Continuous,None,None,None,no
14,days_to_next_dividend,Feature,Integer,None,None,None,no
15,percent_return_next_dividend,Feature,Continuous,None,None,None,no

*Here we see the variable information of the dataset, in total 15 variables*

In [3]:
df = X
display(df.head())
print(df.dtypes)

,quarter,stock,date,open,high,low,close,volume,percent_change_price,percent_change_volume_over_last_wk,previous_weeks_volume,next_weeks_open,next_weeks_close,days_to_next_dividend,percent_return_next_dividend
0,1,AA,1/7/2011,$15.82,$16.72,$15.78,$16.42,239655616,3.79267,NaN,NaN,$16.71,$15.97,26,0.182704
1,1,AA,1/14/2011,$16.71,$16.71,$15.64,$15.97,242963398,-4.42849,1.380223,239655616.0,$16.19,$15.79,19,0.187852
2,1,AA,1/21/2011,$16.19,$16.38,$15.60,$15.79,138428495,-2.47066,-43.024959,242963398.0,$15.87,$16.13,12,0.189994
3,1,AA,1/28/2011,$15.87,$16.63,$15.82,$16.13,151379173,1.63831,9.355500,138428495.0,$16.18,$17.14,5,0.185989
4,1,AA,2/4/2011,$16.18,$17.39,$16.18,$17.14,154387761,5.93325,1.987452,151379173.0,$17.33,$17.37,97,0.175029

quarter                                 int64
stock                                  object
date                                   object
open                                   object
high                                   object
low                                    object
close                                  object
volume                                  int64
percent_change_price                  float64
percent_change_volume_over_last_wk    float64
previous_weeks_volume                 float64
next_weeks_open                        object
next_weeks_close                       object
days_to_next_dividend                   int64
percent_return_next_dividend          float64
dtype: object

In [4]:
import pandas as pd
from ucimlrepo import fetch_ucirepo

dow_jones_index = fetch_ucirepo(id=312)
df = dow_jones_index.data.features.copy()

# Here I'm cleaning up the data, namely removing the $ signs and converting to floats
price_cols = ["open", "high", "low", "close", "next_weeks_open", "next_weeks_close"]
for col in price_cols:
    df[col] = df[col].str.replace("$", "", regex=False).astype(float)

# Dropping missing values too
df["date"] = pd.to_datetime(df["date"])
df = df.dropna()

display(df.head())
print(df.dtypes)

,quarter,stock,date,open,high,low,close,volume,percent_change_price,percent_change_volume_over_last_wk,previous_weeks_volume,next_weeks_open,next_weeks_close,days_to_next_dividend,percent_return_next_dividend
1,1,AA,2011-01-14,16.71,16.71,15.64,15.97,242963398,-4.428490,1.380223,239655616.0,16.19,15.79,19,0.187852
2,1,AA,2011-01-21,16.19,16.38,15.60,15.79,138428495,-2.470660,-43.024959,242963398.0,15.87,16.13,12,0.189994
3,1,AA,2011-01-28,15.87,16.63,15.82,16.13,151379173,1.638310,9.355500,138428495.0,16.18,17.14,5,0.185989
4,1,AA,2011-02-04,16.18,17.39,16.18,17.14,154387761,5.933250,1.987452,151379173.0,17.33,17.37,97,0.175029
5,1,AA,2011-02-11,17.33,17.48,16.97,17.37,114691279,0.230814,-25.712195,154387761.0,17.39,17.28,90,0.172712

quarter                                        int64
stock                                         object
date                                  datetime64[ns]
open                                         float64
high                                         float64
low                                          float64
close                                        float64
volume                                         int64
percent_change_price                         float64
percent_change_volume_over_last_wk           float64
previous_weeks_volume                        float64
next_weeks_open                              float64
next_weeks_close                             float64
days_to_next_dividend                          int64
percent_return_next_dividend                 float64
dtype: object

Succesfully got rid of the $ signs, and data types changed to float as can be seen in this nice comparison

In [5]:
# Here i export data into .csv
os.makedirs("exports", exist_ok=True)
df.to_csv("exports/dow_jones_raw.csv", index=False)

In [ ]:
# RUN THIS TO GET THE RAW DATA
# To skip data fetching, you can load the data directly by uncommenting the code below

# df = pd.read.csv("exports/dow_jones_raw.csv")

### *AI Usage*
AI was used to mainly troubleshoot some issues, but also to improve some individual lines of code. I also used ChatGPT to create the descriptive visuals in the beginning, mainly because I wanted to experiment. I'm not a 100% sure thats ok, but since it is not code I will assume it is, since it's not stated otherwise anywhere.

*Sorry to the reader of this notebook, I ran out of time. Have fun with what's here!*